### ISSUE TITLE
Feature Request: version: latest | main

### ISSUE THREAD

**Issue by matiwinnetou** [aiken-lang/setup-aiken#1]
```
      - uses: aiken-lang/setup-aiken@v0.1.0
        with:
          version: latest
```

```
      - uses: aiken-lang/setup-aiken@v0.1.0
        with:
          version: main
```

**latest** - indicates latest released version
**main** - indicates the latest version in the main branch

**Comment by rvcas** [comment]
I don't want this to depend on Cargo or have to build aiken from source at all. If you want latest main you can just use one of the rust actions and build it from source manually.

Now if we were to have a nightly build on aiken, we could have a build job that creates binaries for latest main, constantly move the tag, and edit a GitHub release.

All this action does is download the correct binary from a GitHub release and I don't intend on it doing anything more than that.
